# - name: variables from inventory
#   hosts: frontend 
#   tasks:
#   - name: print the information
#     ansible.builtin.debug:
#       msg: "Hello iam learning {{ COURSE }}, Duration is: {{ DURATION }} Trainer is: {{ TRAINER }}"


- name: variables from inventory
  hosts: frontend
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "Hello I am learning {{ COURSE }}, Duration: {{ DURATION }}, Trainer is: {{ TRAINER }}"