- name: install packages
  hosts: frontend
  become: yes
  tasks:
  - name: install packages
    ansible.buitlin.package:
      name: "{{ item }}"
      state: present
    loop:
    - mysql
    - nginx
    - zip
