- name: installing packages
  hosts: frontend
  become: yes
  tasks:
  - name: install packages
    ansible.buitlin.debug:
    name: "{{ item }}"
    state: present
  loop:
  - mysql
  - nginx
  - zip