- name: install nginx
  hosts: dynamic_frontend
  become: yes
  tasks:
    - name: insall nginx
      ansible.builtin.dnf:
        name: nginx
        state: installed

    - name: run nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes