- name: craete ec2 and route53 records
  hosts: local 
  connection: local
  vars:
    instances:
    - mysql
    - backend
    - frontend
    subnet_id: subnet-001dcc5c605285812
    sg_id: sg-02ee33accb91fcb0a
  tasks:
  - name: create ec2
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: ami-09c813fb71547fc4f
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"